# Generated by Django 6.0.3 on 2026-04-02 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Biodata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("npm", models.CharField(max_length=16)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BiodataTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Change date"),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="Enabled")),
                (
                    "primary_color",
                    models.CharField(
                        choices=[
                            ("#6C63FF", "Purple"),
                            ("#0F6E56", "Teal"),
                            ("#D85A30", "Coral"),
                            ("#185FA5", "Blue"),
                        ],
                        default="#6C63FF",
                        help_text="Warna utama tampilan website",
                        max_length=20,
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        choices=[
                            ("sans-serif", "Default"),
                            ("Georgia, serif", "Georgia"),
                            ("Verdana, sans-serif", "Verdana"),
                            ("Courier New, monospace", "Courier New"),
                        ],
                        default="sans-serif",
                        help_text="Font yang digunakan di seluruh website",
                        max_length=100,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biodata Theme",
            },
        ),
    ]
