# Generated by Django 5.2.8 on 2026-04-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biodata_kelompok", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biodatatheme",
            options={"verbose_name": "Biodata Theme"},
        ),
        migrations.AddField(
            model_name="biodatatheme",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("sans-serif", "Default"),
                    ("Georgia, serif", "Georgia"),
                    ("Verdana, sans-serif", "Verdana"),
                    ("Courier New, monospace", "Courier New"),
                ],
                default="sans-serif",
                help_text="Font yang digunakan di seluruh website",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="biodatatheme",
            name="primary_color",
            field=models.CharField(
                choices=[
                    ("#6C63FF", "Purple"),
                    ("#0F6E56", "Teal"),
                    ("#D85A30", "Coral"),
                    ("#185FA5", "Blue"),
                ],
                default="#6C63FF",
                help_text="Warna utama tampilan website",
                max_length=20,
            ),
        ),
    ]
