# Generated by Django 5.2.8 on 2026-04-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "biodata_kelompok",
            "0002_alter_biodatatheme_options_biodatatheme_font_family_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="biodata",
            name="nama",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="biodata",
            name="npm",
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
