# Generated by Django 5.2.8 on 2026-04-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biodata_kelompok", "0003_biodata_nama_biodata_npm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biodata",
            name="bio",
        ),
    ]
